### ISSUE TITLE
ld: warning: directory not found for option '-L./lib'

### ISSUE THREAD

**Issue by hinkelman** [tonyg/racket-ansi#5]
When installing racket-ansi on macOS, I get the warning shown in the title. Here is the raco setup output: 

```
raco setup: pre-installing: <pkgs>/ansi/ansi (ansi)
make: making /Users/travishinkelman/Library/Racket/7.2/pkgs/ansi/ansi/private/compiled/native/x86_64-macosx/3m/tty-raw-extension.c because /Users/travishinkelman/Library/Racket/7.2/pkgs/ansi/ansi/private/compiled/native/x86_64-macosx/3m/tty-raw-extension.c does not exist
xform-cpp: (/usr/bin/gcc -E -DOS_X -DMZ_PRECISE_GC -I./include -I/Users/travishinkelman/Library/Racket/7.2/pkgs/ansi/ansi/private/ -I/Applications/Racket v7.2/include -I/Applications/Racket v7.2/include -DMZ_XFORM -DMZ_PRECISE_GC -DGC_STACK_CALLEE_RESTORE tty-raw-extension.c)
make: making compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.o because compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.o does not exist
compile-extension: (/usr/bin/gcc -c -O2 -fPIC -fno-common -DOS_X -DMZ_PRECISE_GC -I./include -I/Applications/Racket v7.2/include /Users/travishinkelman/Library/Racket/7.2/pkgs/ansi/ansi/private/compiled/native/x86_64-macosx/3m/tty-raw-extension.c -o compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.o)
make: making compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.dylib because compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.dylib does not exist
link-extension: (/usr/bin/gcc -bundle -flat_namespace -undefined suppress -L./lib compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.o /Applications/Racket v7.2/lib/mzdyn3m.o -o compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.dylib)
ld: warning: directory not found for option '-L./lib'
make: made /Users/travishinkelman/Library/Racket/7.2/pkgs/ansi/ansi/private/compiled/native/x86_64-macosx/3m/tty-raw-extension.c
make: made compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.o
make: made compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.dylib
```

When ansi is loaded in DrRacket, I get this message:

```
default-load-extension-handler: forbidden (execute) access to /Users/travishinkelman/Library/Racket/7.2/pkgs/ansi/ansi/private/compiled/native/x86_64-macosx/3m/tty-raw-extension_ss.dylib
```

These warnings don't seem to present a problem to running the little bit of my code that depends on the raart module. And I realize that it might not be specific to the ansi package. I'm new to Racket and not sure how to troubleshoot this particular problem so starting here. 

Thanks.

**Comment by tonyg** [comment]
Thanks for writing. I'm afraid I don't have ready access to a mac to experiment on, but I think the `ld` warning is harmless. I'm a bit more worried by the `default-load-extension-handler` message, though! When you have `ansi` installed, are you able to run `ansi/test-raw.rkt` successfully?

**Comment by hinkelman** [comment]
I'm not sure how to determine if `ansi/test-raw.rkt` is running successfully. Here is a screenshot (I typed 'test' in the text box):

<img width="1210" alt="Screen Shot 2019-04-26 at 4 59 41 AM" src="https://user-images.githubusercontent.com/3461540/56806305-5cdf8b00-67e0-11e9-850f-9c81b56bec67.png">

**Comment by tonyg** [comment]
Hm, I'm not sure what I'd expect from running it in DrRacket, but that looks actually surprisingly OK. (Did pressing Control-D terminate the program session, like the printed message suggests it should?) Can you try in a console/shell window?

**Comment by hinkelman** [comment]
No, control-D did not terminate in DrRacket. Here's what it looks like in the terminal and control-D works there:

<img width="249" alt="Screen Shot 2019-04-26 at 5 14 38 AM" src="https://user-images.githubusercontent.com/3461540/56806936-3a4e7180-67e2-11e9-9585-bf18be602880.png">

It looks like it is not really an issue. Thanks.

**Comment by tonyg** [comment]
OK, thanks for checking! One more thing, did you see that `default-load-extension-handler` message when you want `test-raw.rkt` in a terminal?

**Comment by hinkelman** [comment]
The `default-load-extension-handler` message is only shown in the margin of DrRacket window, not in the DrRacket interactions pane or the terminal.

**Comment by tonyg** [comment]
Thanks. In that case I think everything looks to be working fine.
